version: '3'

services:
  api:
    build: .
    container_name: api-service
    ports:
      - 80:8080
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: api-database
    restart: unless-stopped
    tty: true
    ports:
      - 4306:3306
    environment:
      MYSQL_DATABASE: journal

  admin:
    image: adminer
    container_name: dbadmin
    ports:
      - "8080:8080"